name = "Blockerphile"
author = "Ryan Wong"
version = "0.1.0-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71402c33ea380ec68d0fa180fca92029e69b74937305fd3a5a05915517b18e8b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
