name = "Happy Minecraft Modpack"
author = "Ryan Wong"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29fc6a4d496ef4d8b180fd396609c63934133fcb1d1868b4dd79ffc724eeec43"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
