name = "Blockerphile"
author = "Ryan Wong"
version = "0.1.0-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e440a816990536dc8e9b2864af5cbc4ccd8a7f8bd5b64dfbd1a7de6b0d398d7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
